#pragma once

#define IDI_APP_ICON 101

// Use numbers well above 100 to avoid conflicts with system resources.
// Each resource needs a unique ID.
#define ID_IMAGE_HAPPY 201
#define ID_IMAGE_NEUTRAL  202
#define ID_IMAGE_GRIMACE_TWO_SWEAT     203
#define ID_IMAGE_ANGUISH  204
#define ID_IMAGE_ANGUISH_VERY  205
#define ID_IMAGE_ANGUISH_EXTREMELY  206
#define ID_IMAGE_TIRED  207
#define ID_IMAGE_TIRED_VERY  208
#define ID_IMAGE_TIRED_EXTREMELY  209
#define ID_IMAGE_PLEASED  210
#define ID_IMAGE_SURPRISED  211
#define ID_IMAGE_GRIMACE  212
#define ID_IMAGE_HAPPY_BLINK 301
#define ID_IMAGE_NEUTRAL_BLINK  302
#define ID_IMAGE_GRIMACE_TWO_SWEAT_BLINK     303
#define ID_IMAGE_ANGUISH_BLINK  304
#define ID_IMAGE_ANGUISH_VERY_BLINK  305
#define ID_IMAGE_TIRED_VERY_BLINK  306
